#!/bin/bash
set -e

# ========================================
# AWS EKS Cluster Setup (No Terraform!)
# ========================================
# Creates: EKS Cluster with managed node groups
# Uses: eksctl, AWS CLI
# ========================================

echo "=========================================="
echo "🚀 Creating AWS EKS Cluster"
echo "   (No Terraform - Using eksctl)"
echo "=========================================="

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

# Functions
print_green() { echo -e "${GREEN}✅ $1${NC}"; }
print_yellow() { echo -e "${YELLOW}⚠️  $1${NC}"; }
print_red() { echo -e "${RED}❌ $1${NC}"; }
print_blue() { echo -e "${BLUE}ℹ️  $1${NC}"; }

# Load environment variables
if [ -f ~/.openstack-foodhub.env ]; then
    source ~/.openstack-foodhub.env
fi

# Configuration
CLUSTER_NAME=${CLUSTER_NAME:-"foodhub-eks"}
AWS_REGION=${AWS_REGION:-"ap-southeast-1"}
K8S_VERSION=${K8S_VERSION:-"1.28"}
NODE_TYPE=${NODE_TYPE:-"t3.medium"}
NODE_COUNT=${NODE_COUNT:-2}
NODE_MIN=${NODE_MIN:-2}
NODE_MAX=${NODE_MAX:-4}
VPC_CIDR=${AWS_VPC_CIDR:-"10.1.0.0/16"}

# ========================================
# Step 0: Check Prerequisites
# ========================================
echo ""
echo "Step 0: Checking prerequisites..."

# Check AWS CLI
if ! command -v aws &> /dev/null; then
    print_red "AWS CLI is not installed"
    echo "Please install: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
    exit 1
fi
print_green "AWS CLI found"

# Check eksctl
if ! command -v eksctl &> /dev/null; then
    print_yellow "eksctl not found, installing..."
    # Install eksctl
    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
    sudo mv /tmp/eksctl /usr/local/bin
    print_green "eksctl installed"
else
    print_green "eksctl found"
fi

# Check kubectl
if ! command -v kubectl &> /dev/null; then
    print_red "kubectl is not installed"
    echo "Please install: https://kubernetes.io/docs/tasks/tools/"
    exit 1
fi
print_green "kubectl found"

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    print_red "AWS credentials not configured"
    echo "Please run: aws configure"
    exit 1
fi
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
print_green "AWS Account: ${AWS_ACCOUNT_ID}"

# ========================================
# Step 1: Check if cluster already exists
# ========================================
echo ""
echo "Step 1: Checking if cluster exists..."

if eksctl get cluster --name ${CLUSTER_NAME} --region ${AWS_REGION} 2>/dev/null | grep -q ${CLUSTER_NAME}; then
    print_yellow "Cluster ${CLUSTER_NAME} already exists"
    
    # Update kubeconfig
    aws eks update-kubeconfig --name ${CLUSTER_NAME} --region ${AWS_REGION}
    print_green "Kubeconfig updated"
    
    # Show cluster info
    echo ""
    echo "Cluster Info:"
    kubectl cluster-info
    
    echo ""
    echo "Nodes:"
    kubectl get nodes
    
    exit 0
fi

# ========================================
# Step 2: Create EKS Cluster
# ========================================
echo ""
echo "Step 2: Creating EKS cluster..."
echo "   This will take 15-20 minutes..."
echo ""

cat > /tmp/eks-cluster-config.yaml <<EOF
# EKS Cluster Configuration
# Generated by 01-create-eks-cluster.sh
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_REGION}
  version: "${K8S_VERSION}"

vpc:
  cidr: ${VPC_CIDR}
  nat:
    gateway: Single
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

iam:
  withOIDC: true

managedNodeGroups:
  - name: ${CLUSTER_NAME}-workers
    instanceType: ${NODE_TYPE}
    desiredCapacity: ${NODE_COUNT}
    minSize: ${NODE_MIN}
    maxSize: ${NODE_MAX}
    volumeSize: 50
    volumeType: gp3
    privateNetworking: true
    labels:
      role: worker
      environment: production
    tags:
      Project: foodhub
      Environment: production
      ManagedBy: eksctl
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        efs: true
        albIngress: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler

addons:
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver
EOF

print_blue "Cluster configuration saved to /tmp/eks-cluster-config.yaml"

# Create cluster
echo ""
echo "Creating cluster with eksctl..."
eksctl create cluster -f /tmp/eks-cluster-config.yaml

# ========================================
# Step 3: Verify Cluster
# ========================================
echo ""
echo "Step 3: Verifying cluster..."

# Update kubeconfig
aws eks update-kubeconfig --name ${CLUSTER_NAME} --region ${AWS_REGION}
print_green "Kubeconfig updated"

# Check nodes
echo ""
echo "Nodes:"
kubectl get nodes -o wide

# Check cluster info
echo ""
echo "Cluster Info:"
kubectl cluster-info

# ========================================
# Step 4: Install AWS Load Balancer Controller
# ========================================
echo ""
echo "Step 4: Installing AWS Load Balancer Controller..."

# Create IAM Policy
POLICY_NAME="AWSLoadBalancerControllerIAMPolicy"
if ! aws iam get-policy --policy-arn arn:aws:iam::${AWS_ACCOUNT_ID}:policy/${POLICY_NAME} 2>/dev/null; then
    curl -o /tmp/iam_policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.6.1/docs/install/iam_policy.json
    aws iam create-policy \
        --policy-name ${POLICY_NAME} \
        --policy-document file:///tmp/iam_policy.json
    print_green "IAM Policy created"
else
    print_yellow "IAM Policy already exists"
fi

# Create service account
eksctl create iamserviceaccount \
    --cluster=${CLUSTER_NAME} \
    --namespace=kube-system \
    --name=aws-load-balancer-controller \
    --attach-policy-arn=arn:aws:iam::${AWS_ACCOUNT_ID}:policy/${POLICY_NAME} \
    --override-existing-serviceaccounts \
    --approve

# Install using Helm
if ! command -v helm &> /dev/null; then
    print_yellow "Helm not found, installing..."
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
fi

helm repo add eks https://aws.github.io/eks-charts
helm repo update

helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
    -n kube-system \
    --set clusterName=${CLUSTER_NAME} \
    --set serviceAccount.create=false \
    --set serviceAccount.name=aws-load-balancer-controller

print_green "AWS Load Balancer Controller installed"

# ========================================
# Step 5: Create Namespaces
# ========================================
echo ""
echo "Step 5: Creating namespaces..."

kubectl create namespace foodhub --dry-run=client -o yaml | kubectl apply -f -
kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

print_green "Namespaces created"

# ========================================
# Summary
# ========================================
echo ""
echo "=========================================="
echo "🎉 EKS Cluster Created Successfully!"
echo "=========================================="
echo ""
echo "📋 Cluster Details:"
echo "   Name:           ${CLUSTER_NAME}"
echo "   Region:         ${AWS_REGION}"
echo "   K8s Version:    ${K8S_VERSION}"
echo "   Nodes:          ${NODE_COUNT} x ${NODE_TYPE}"
echo "   VPC CIDR:       ${VPC_CIDR}"
echo ""
echo "🔧 Components Installed:"
echo "   ✅ EKS Cluster"
echo "   ✅ Managed Node Group"
echo "   ✅ VPC CNI"
echo "   ✅ CoreDNS"
echo "   ✅ AWS Load Balancer Controller"
echo "   ✅ EBS CSI Driver"
echo ""
echo "📂 Namespaces:"
echo "   ✅ foodhub"
echo "   ✅ argocd"
echo "   ✅ monitoring"
echo ""
echo "🔍 Next Steps:"
echo "   1. Create ECR repositories:"
echo "      ./02-create-ecr-repos.sh"
echo ""
echo "   2. Create RDS PostgreSQL:"
echo "      ./03-create-rds-postgresql.sh"
echo ""
echo "   3. Setup VPN connection:"
echo "      ./01-create-vpn.sh (already exists)"
echo ""
echo "=========================================="

# Save configuration
cat > /tmp/foodhub-eks-config.sh <<EOF
# Auto-generated by 01-create-eks-cluster.sh
export CLUSTER_NAME="${CLUSTER_NAME}"
export AWS_REGION="${AWS_REGION}"
export AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID}"
export K8S_VERSION="${K8S_VERSION}"
export VPC_CIDR="${VPC_CIDR}"
export EKS_VPC_ID=$(aws eks describe-cluster --name ${CLUSTER_NAME} --query "cluster.resourcesVpcConfig.vpcId" --output text)
EOF

print_green "Configuration saved to /tmp/foodhub-eks-config.sh"
