apiVersion: v1
kind: Service
metadata:
  name: foodhub-frontend
  labels:
    app: foodhub-frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: foodhub-frontend
